In [1]:
import pandas as pd

# States
states = ["S1", "S2", "S3"]

# Transition Probabilities
transition_probabilities = {
    ("S1", "A1", "S2"): 0.6,
    ("S1", "A1", "S3"): 0.2,
    ("S1", "A2", "S2"): 0.4,
    ("S1", "A2", "S3"): 0.8,

    ("S2", "A1", "S1"): 0.7,
    ("S2", "A1", "S3"): 0.5,
    ("S2", "A2", "S1"): 0.3,
    ("S2", "A2", "S3"): 0.5,

    ("S3", "A1", "S1"): 0.9,
    ("S3", "A1", "S2"): 0.4,
    ("S3", "A2", "S1"): 0.1,
    ("S3", "A2", "S2"): 0.6
}

# Display transition matrix for each action
for action in ["A1", "A2"]:

    matrix = pd.DataFrame(0.0, index=states, columns=states)

    for (current_state, act, next_state), prob in transition_probabilities.items():
        if act == action:
            matrix.loc[current_state, next_state] = prob

    print("=" * 50)
    print(f"TRANSITION PROBABILITY MATRIX ({action})")
    print("=" * 50)
    display(matrix)

==================================================
TRANSITION PROBABILITY MATRIX (A1)
==================================================

     S1   S2   S3
S1  0.0  0.6  0.2
S2  0.7  0.0  0.5
S3  0.9  0.4  0.0

==================================================
TRANSITION PROBABILITY MATRIX (A2)
==================================================

     S1   S2   S3
S1  0.0  0.4  0.8
S2  0.3  0.0  0.5
S3  0.1  0.6  0.0